apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: pegasusbi/com:BUILD_NUMBER
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
